[project]
name = "flet-stt-demo"
version = "0.1.1"
description = "Demo app for flet-stt"
requires-python = ">=3.11"
dependencies = [
    "flet>=0.82.0",
]

[tool.flet.android.permission]
"android.permission.RECORD_AUDIO" = true

[tool.flet.app]
exclude = ["flet_stt"]


[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11"
flet = ">=0.82.0"
flet-stt = {path = "flet_stt", develop = true}

[tool.flet.dev_packages]
flet-stt = "flet_stt"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
